### ISSUE TITLE
Some domains should not be in this list

### ISSUE THREAD

**Issue by hntee** [kslr/disposable-email-domains#41]
Hi, this project is really helpful.
However, I found some domains in `list.txt`, which do not seem to be spam domains.
Please take a look at these.

```
139.com
nus.edu.sg
benilde.edu.ph
zoho.com
```

**Comment by kslr** [comment]
thanks, https://github.com/kslr/disposable-email-domains/commit/6aef10a30e59e9fd8965869a196dd8d6b37a54d8
