### ISSUE TITLE
Inclusion of SimpleLogin domains in your list of disposable domains

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [kslr/disposable-email-domains#61]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that some of our domains are present your list of disposable emails. To be more precise, slmail.me, 8alias.com, dralias.com, 8shield.net, are included.

At Proton, we take anti-abuse especially seriously and would like to work with you on having the abovementioned domains removed from your list. Can you elaborate why these domains are incorporated? Would it be possible to correct this?

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

**Comment by kslr** [comment]
I agree.As long as mail address are non-reusable, they should not be considered disposable.

**Comment by Nikola-Test-for-Proton** [comment]
Hi,

This is a follow-up. 

I can see that our 8alias.com domain is still on your list.

Could we have this rectified soon?

Looking forward to your reply.

Have a pleasant day.
